/* tslint:disable */
/* eslint-disable */
/**
 * Search API
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum FieldOperator {
    Equal = '=',
    EqualEqual = '==',
    LessThan = '<',
    LessThanOrEqualTo = '<=',
    GreaterThan = '>',
    GreaterThanOrEqualTo = '>=',
    PercentEqual = '%=',
    TildeEqual = '~=',
    SlashEqual = '/=',
    StarEqual = '*='
}

export function FieldOperatorFromJSON(json: any): FieldOperator {
    return FieldOperatorFromJSONTyped(json, false);
}

export function FieldOperatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): FieldOperator {
    return json as FieldOperator;
}

export function FieldOperatorToJSON(value?: FieldOperator | null): any {
    return value as any;
}

